server:
  port: 8080

spring:
  application:
    name: ZhabBot
  liquibase:
    enabled: false
    change-log: db-migration/liquidbase-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zhab_bot_db
    username: dany
    password: dany
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

bot:
  name: t.me/zhab_bot
  token: 7020627923:AAGu5F4WGyL6UxfQMc4-wDN9_r4j_a-fl7M