server:
  port: 2020
  servlet:
    context-path: /zhabalaka

spring:
  application:
    name: ZhabBot
  liquibase:
    enabled: true
    change-log: db-migration/liquidbase-master.xml
    default-schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zhab-bot
    username: zhab
    password: zhab

springdoc:
  api-docs:
    enabled: true

logging:
  level:
    root: info
    ru.mkhamkha: debug

bot-properties:
  name: t.me/zhab_bot
  token: 7020627923:AAGu5F4WGyL6UxfQMc4-wDN9_r4j_a-fl7M