CREATE SCHEMA IF NOT EXISTS storage;

CREATE TABLE IF NOT EXISTS storage.logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY                         NOT NULL,
    key             TEXT                                                            NOT NULL,
    value           TEXT                                                            NOT NULL,

    CONSTRAINT pk_logs PRIMARY KEY (id)
);