CREATE SCHEMA IF NOT EXISTS zhab;

CREATE TABLE zhab.follower
(
    id          BIGINT                                                                                      NOT NULL,
    name        VARCHAR(255)                                                                                NOT NULL,
    family      VARCHAR(255)                                                                                NOT NULL,
    create_time TIMESTAMP                                                                                   NOT NULL,

    CONSTRAINT pk_follower PRIMARY KEY (id)
);

CREATE TABLE zhab.news
(
    id          BIGINT                  GENERATED BY DEFAULT AS IDENTITY                                    NOT NULL,
    title       VARCHAR(250)                                                                                NOT NULL,
    message     VARCHAR(2000)                                                                               NOT NULL,
    create_time TIMESTAMP                                                                                   NOT NULL,

    CONSTRAINT pk_news PRIMARY KEY (id)
);