CREATE TABLE IF NOT EXISTS zhab.logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY                         NOT NULL,
    level           VARCHAR(5)                                                      NOT NULL,
    logger          VARCHAR(250)                                                    NOT NULL,
    message         TEXT                                                            NOT NULL,
    create_time     TIMESTAMP                                                       NOT NULL,

    CONSTRAINT pk_logs PRIMARY KEY (id)
);